image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

service:
  name: postgresql
  type: ClusterIP
  port: 5432

database:
  createSecret: false
  name: globallyhub
  username: globallyhub
  password: change-me
  schema: public

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  fsGroup: 999

securityContext:
  runAsUser: 999
  runAsGroup: 999
  runAsNonRoot: true

nodeSelector: {}

tolerations: []

affinity: {}
