{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: globallyhub-db
  labels:
    app.kubernetes.io/name: globallyhub-postgresql
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_SCHEMA: {{ .Values.database.schema | quote }}
{{- end }}
