apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: globallyhub-postgresql
    app.kubernetes.io/managed-by: Helm

spec:
  type: {{ .Values.service.type }}

  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP

  selector:
    app.kubernetes.io/name: globallyhub-postgresql
